context:
  version: "1.0.0"

package:
  name: symbolite
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/s/symbolite/symbolite-${{ version }}.tar.gz
  sha256: f1df9d3fe4a289385494b2622c05bcc9332c9002171bd9f671dcc90427396d59

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
  - python >=3.12
  - uv-build
  - pip
  run:
  - python >=3.12

tests:
- python:
    imports:
    - symbolite
    pip_check: true

about:
  homepage: https://github.com/dyscolab/symbolite
  license: MIT
  license_file: LICENSE
  summary: A minimalistic symbolic package.
  description: |
    ![Package](https://img.shields.io/pypi/v/symbolite?label=symbolite)
    ![CodeStyle](https://img.shields.io/badge/code%20style-black-000000.svg)
    ![License](https://img.shields.io/pypi/l/symbolite?label=license)
    ![PyVersion](https://img.shields.io/pypi/pyversions/symbolite?label=python)
    [![CI](https://github.com/dyscolab/symbolite/actions/workflows/ci.yml/badge.svg)](https://github.com/dyscolab/symbolite/actions/workflows/ci.yml)

    # symbolite: a minimalistic symbolic python package

extra:
  recipe-maintainers:
    - maurosilber
    - hgrecco
